GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
    "author": "Siriel Wafa",
    "title": "The Holy Trinity",
    "url": "https://Karyaku/api/bacaan/The-Holy-Trinity",
    "upvotes": 5
}
###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
    "author": "John Doe",
    "title": "Introduction to Express",
    "url": "https://example.com/express-intro",
    "upvotes": 10
}