GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/info/
###
GET http://localhost:3001/api/persons/6811f00b90e500613d78af7a
###
GET http://localhost:3001/api/persons/5
###
DELETE http://localhost:3001/api/persons/4a
###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Siriel Wafa",
    "number": "0987687643"
}

