GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/info/
###
GET http://localhost:3001/api/persons/6811f00b90e500613d78af7a
###
GET http://localhost:3001/api/persons/5a
###
DELETE http://localhost:3001/api/persons/68123f3ccd3ab69e765315ea
###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Siriel Wafa",
    "number": "1234556"
}
###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Siriel Wafas",
    "number": "040-22334455"
}
###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Siriel Wafa",
    "number": "10-22-334455"
}
